import { jsPDF } from 'jspdf'

export function exportQuoteToPDF(config, quoteDetails, thrust) {
  const doc = new jsPDF('p', 'mm', 'a4')

  // Colors & Brand
  const primaryColor = [0, 255, 170]
  const darkBg = [20, 20, 25]

  // Header Background
  doc.setFillColor(darkBg[0], darkBg[1], darkBg[2])
  doc.rect(0, 0, 210, 40, 'F')

  // Header Title
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('OPENFPV PILOT', 14, 20)

  // Subtitle
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2])
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text('Custom Build Quotation', 14, 28)

  // Date & Ref
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  const dateStr = new Date().toLocaleDateString()
  doc.text(`Date: ${dateStr}`, 155, 20)
  doc.text(`Ref: FPV-${Math.floor(Math.random() * 10000)}`, 155, 26)

  // Performance Specs
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Build Performance Specification:', 14, 55)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(`Estimated Thrust: ${thrust}`, 14, 65)
  doc.text(`Base Frame Size: ${config.frameSize}`, 14, 72)
  doc.text(`Target Battery Protocol: ${config.batteryCell}`, 14, 79)

  // Draw Custom Table
  let startY = 95

  // Table Header Background
  doc.setFillColor(darkBg[0], darkBg[1], darkBg[2])
  doc.rect(14, startY - 6, 182, 10, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('S/No', 16, startY)
  doc.text('Component Type', 30, startY)
  doc.text('Component Name', 75, startY)
  doc.text('Qty', 145, startY)
  doc.text('Unit Cost', 160, startY)
  doc.text('Total', 182, startY)

  startY += 8
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')

  quoteDetails.items.forEach((item, index) => {
    const splitName = doc.splitTextToSize(item.name, 65)

    // Check page break
    if (startY + (splitName.length * 5) > 270) {
      doc.addPage()
      startY = 20
    }

    doc.text(String(index + 1), 18, startY)
    doc.text(item.type, 30, startY)
    doc.text(splitName, 75, startY)
    doc.text(String(item.qty), 148, startY)
    doc.text(`$${item.unitPrice.toFixed(2)}`, 160, startY)
    doc.text(`$${item.total.toFixed(2)}`, 182, startY)

    // Draw row separator
    const rowHeight = splitName.length * 5 + 2
    doc.setDrawColor(220, 220, 220)
    doc.line(14, startY + rowHeight - 3, 196, startY + rowHeight - 3)

    startY += rowHeight + 2
  })

  // Table Footer (Total)
  doc.setFillColor(240, 240, 240)
  doc.rect(14, startY, 182, 12, 'F')
  doc.setFont('helvetica', 'bold')
  doc.text('Est. Total Quote:', 110, startY + 8)

  const formattedUSD = `$${quoteDetails.grandTotal.toFixed(2)}`
  const formattedINR = `(≈ ₹${Math.round(quoteDetails.grandTotalINR).toLocaleString('en-IN')})`

  doc.text(`${formattedUSD}  ${formattedINR}`, 150, startY + 8)

  // Footer Watermark
  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 150)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by OpenFPV Pilot — Free Open-Source Learning Platform', 14, pageHeight - 10)

  // Save PDF
  const safeFrame = (config.frameSize || 'Build').replace(/[^a-zA-Z0-9]/g, '_')
  const safeVideo = (config.vtxModel || 'Standard').replace(/[^a-zA-Z0-9]/g, '_')
  doc.save(`OpenFPV_Quote_${safeFrame}_${safeVideo}.pdf`)
}
